### PR TITLE
Pep8 fixes, sort fixes and general refactoring.

### PR DESCRIPTION
**Pull request by shashank88**

### CODE REVIEW

**Comment by maverickjoy** [comment]
Hi @shashank88 ,
As mentioned in the earlier discussion, you are again making the same kind of mistake.
I guess you should understand preference based sorting first (Its part of algorithms) before making any further changes.
Anyway @FerreroJeremy  Ill leave it on you to decide.

RESULTS :
 
	l1 = ["abc sd","dsfds dsfds","asdasdfa","as","a a a","asd abd abc","b b b"]
	l2 = ["abc sd","dsfds dsfds","asdasdfa","as","a a a","asd abd abc","b b b"]

	def _myCmp(s1,s2):
	    # if len(s1.split()) == 1 and len(s2.split()) == 1:
	    if len(s1.split()) == len(s2.split()) :
		if len(s1) >= len(s2) :
		    return 1
		else:
		    return -1
	    else:
		if len(s1.split()) >= len(s2.split()):
		    return 1
		else:
		    return -1


	print "l1 : ",sorted(l1, key=lambda s: (len(s.split()), s), reverse=True) # Wrong Implementation

	print "l2 : ",sorted(l2,cmp=_myCmp,reverse=True) # Right Implementation

	# OUTPUT

	# l1 :  ['b b b', 'asd abd abc', 'a a a', 'dsfds dsfds', 'abc sd', 'asdasdfa', 'as']
	# l2 :  ['asd abd abc', 'a a a', 'b b b', 'dsfds dsfds', 'abc sd', 'asdasdfa', 'as']

**Comment by shashank88** [comment]
Hi Vikram,

a) What is this being used for? I don't see this breaking any tests which
is what I base most refactoring on.
b) Python3 doesn't support cmp like C++ or Python2.
c) why do you have: ['asd abd abc', 'a a a', 'b b b', 'dsfds dsfds', 'abc
sd', 'asdasdfa', 'as'] vs ['a a a', 'asd abd abc', 'b b b', 'abc sd',
'dsfds dsfds', 'as', 'asdasdfa'] if you want secondary sorting in lexical
order.

Thanks
Shashank

**Comment by shashank88** [comment]
Is this what you are looking for:
>>> l1
['abc sd', 'dsfds dsfds', 'asdasdfa', 'as', 'a a a', 'asd abd abc', 'b b b']
>>> sorted(sorted(l1), key=lambda s: len(s.split()), reverse=True)
['a a a', 'asd abd abc', 'b b b', 'abc sd', 'dsfds dsfds', 'as', 'asdasdfa']

?

**Comment by maverickjoy** [comment]
Hi,
No, Not  Lexicographically , It doesn't even make sense in value extraction ,but on length basis, 2nd priority is length. I wont be able to explain the whole thing but in a nutshell its for proper substitution which would be taking place. 
So please don't, do this " sorted(sorted(transition_list), key=lambda s: len(s.split()), reverse=True) "

**Comment by maverickjoy** [comment]
Related to Python3 sorting, for multiple key sorting this would help you for this case : 
https://docs.python.org/3/howto/sorting.html

**Comment by maverickjoy** [comment]
Related to Python3 sorting, for multiple key sorting this would help you for this case :
https://docs.python.org/3/howto/sorting.html

It's an important thing, multiple parameter sorting is used in many algorithms, Python cannot miss it :P

**Comment by shashank88** [comment]
I already sent multiple key sorting in the previous diff if you didn't
notice. That's why I am asking for a real world example so I can add unit
tests for it.

Just write the tests which convey what you want rather than giving vague
non real world examples:
example: Currently the code I wrote was for this test case:

def test_parser_sort_length():
    input_list = ['len2 len2', 'len1', 'len3 len3 len3']
    expected = ['len3 len3 len3', 'len2 len2', 'len1']
    assert Parser.transformation_sort(input_list) == expected


def test_parser_sort_length_lexical():
    input_list = ['len2 len2', 'len1', 'len3 len3 len3', 'alen3 alen3
alen3']
    expected = ['alen3 alen3 alen3', 'len3 len3 len3', 'len2 len2', 'len1']

    assert Parser.transformation_sort(input_list) == expected

There is no way to have inverse orderings in 2 keys in Python3 sorting,
hence the double sorted.

**Comment by maverickjoy** [comment]
Hi,
You see , In your case if I give

	input_list = ['len2 len2', 'len1', 'len3 len3 len3', 'zlen3 zlen3 zlen3']
	instead of
	input_list = ['len2 len2', 'len1', 'len3 len3 len3', 'alen3 alen3']

	to -> sorted(sorted(input_list), key=lambda s: len(s.split()), reverse=True)

	The result changes : ['len3 len3 len3', 'zlen3 zlen3 zlen3', 'len2 len2', 'len1']
	Whereas, result should be : ['zlen3 zlen3 zlen3', 'len3 len3 len3', 'len2 len2', 'len1']

Why this is happening is because you are doing it in lexicographical manner,
Secondly even if you manage to do it on the basis of length, the results will be still wrong , why this
because of a very simple thing.

Sorting on priority of parameters is very different than
Sorting the whole list on a parameter than sorting the sorted list on another parameter.
I guess this is as far as could help you :) , this weekend if ill get some time ill write it in a python3 and let you know.

Thanks
Vikram

**Comment by maverickjoy** [comment]
Hi,
You see , In your case if I give

	input_list = ['len2 len2', 'len1', 'len3 len3 len3', 'zlen3 zlen3 zlen3']
	instead of
	input_list = ['len2 len2', 'len1', 'len3 len3 len3', 'alen3 alen3']

	to -> sorted(sorted(input_list), key=lambda s: len(s.split()), reverse=True)

	The result changes : ['len3 len3 len3', 'zlen3 zlen3 zlen3', 'len2 len2', 'len1']
	Whereas, result should be : ['zlen3 zlen3 zlen3', 'len3 len3 len3', 'len2 len2', 'len1']

Why this is happening is because you are doing it in lexicographical manner,
Secondly even if you manage to do it on the basis of length, the results will be still wrong , why this
because of a very simple thing.

- Sorting on priority of parameters is very different than
- Sorting the whole list on a parameter than sorting the sorted list on another parameter.

I guess this is as far as could help you :) , this weekend if ill get some time, ill write it in python3 format and let you know.

Thanks
Vikram

**Pull request merged**
